### ISSUE TITLE
Fatal error when DS-CLI active

### ISSUE THREAD

**Issue by afragen** [ServerPress/ds-cli#3] opened 2016-06-11 19:33 UTC
When I start/restart DesktopServer 3.8.2 with DS-CLI active I get the following fatal error.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/15987072/7cddfa18-2fd0-11e6-8436-b4db68d116f0.png)

When I start/restart with DS-CLI deactivated the error is gone. The first time I started with DS-CLI active I clicked the menubar icon, then I closed terminal window after it opened. Nothing more.

Any thoughts?

**Comment by afragen** [comment] 2016-06-28 17:23
I found the issue. You have included a copy of @rmccue's Request classes. These are included in trunk and unfortunately the version in ds-cli are not up to date. Specifically `Requests_Response::is_redirect()` is not present in the version present in this plugin and is present in trunk.

As a ds-plugin, this is loaded first and results in a fatal error for this method not being available.

**Comment by Steveorevo** [comment] 2016-07-03 19:04
You can export your website to a zip archive for review, support@serverpress.com can reproduce the issue and attempt to eliminate it and/or provide steps to update your install.

**Comment by afragen** [comment] 2016-07-03 23:25
Hey @Steveorevo, it doesn't have anything to do with my particular website and everything to do with trunk and WP4.6

WP 4.5.3 doesn't have `wp-includes/Requests/` and WP 4.6 (trunk) does. Unfortunately DS-CLI includes rmccue's Requests library. An updated version is included in trunk. The included library is not up to date.

If you could only include this library for WP < 4.6 it should work.

**Comment by Steveorevo** [comment] 2016-07-06 23:33
It appears that WP-CLI (included with DS-CLI) references "rmccue/requests": "~1.6". I'll cross check WP-CLI and WP 4.6 to see if we can synchronize.

**Comment by davejesch** [comment] 2016-07-22 18:54
fixed by disabling autoload and hard-loading GString and wp hooks.

**Comment by remkus** [comment] 2016-08-17 10:38
This is especially an issue as of today since this clashes with WordPress 4.6. Wasted a morning to figure out what was going on :(

**Comment by GreggFranklin** [comment] 2018-05-09 15:44
Issue is resolved

**Closed as completed by GreggFranklin** 2018-05-09 15:44 UTC
